// <auto-generated />
using System;
using Bayan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bayan.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This snapshot is intentionally simplified.
            // EF Core will use the configurations from the Data/Configurations folder
            // when applying migrations.

            // The actual model is defined by the entity configurations that are
            // automatically applied via modelBuilder.ApplyConfigurationsFromAssembly()
            // in ApplicationDbContext.OnModelCreating()
#pragma warning restore 612, 618
        }
    }
}
